// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stxrccnzyvuulsadjuob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0eHJjY256eXZ1dWxzYWRqdW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTQ1MDQsImV4cCI6MjA2OTU3MDUwNH0.HTMagpoGKUUPxq04O0MbpV7npgnFRdX30mnQ0K2_gNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});